client/package-lock.json
client/package.json
client/src/components/User/DummyUser.js
client/src/components/User/UserCard.js
client/src/components/User/UserFavourites.js
client/src/components/User/UserInfo.js
client/src/pages/MyPage/MyPage.js
client/src/styles/UserProfile.js

feat: implement user component

---

server/.eslintrc
server/src/controller/home.js
server/src/controller/index.js
server/src/controller/likes.js
server/src/controller/property.js
server/src/controller/user.js
server/src/data/data.js
server/src/middleware/auth.js
server/src/models/home.js
server/src/models/index.js
server/src/models/likes.js
server/src/models/mockHome.js
server/src/models/mockLikes.js
server/src/models/mockProperty.js
server/src/models/property.js
server/src/models/user.js
server/src/routes/home.js
server/src/routes/index.js
server/src/routes/likes.js
server/src/routes/user.js
server/src/services/index.js
server/src/services/likes.js
server/src/services/user.js
server/src/utils/error.js

<br />
- Add Likes backend api to feed mock data to frontend
- Add Middleware auth (email must be sent in header as a token to pass the auth)
```
method: GET,
url: {base_url}/likes,
headers: {
'Authorization': 'Bearer johndoe@gmail.com'
}
```
```
method: 'POST',
url: {base_url}/likes,
'headers': {
'Content-Type': 'application/json',
'Authorization': 'Bearer johndoe@gmail.com'
},
```
body:
```
{
"zpid": 2057115039,
"imgSrc": "https://photos.zillowstatic.com/fp/6bf34c152c53b95c57a6eb3c4f99921a-p_d.jpg",
"address": "523 King Edward Ave W #412, Vancouver, BC V5Z 0J3",
"price": 708000,
"bedrooms": 1,
"bathrooms": 0,
"livingArea": 514,
"propertyType": "CONDO",
"listingStatus": "FOR_SALE",
"unit": "# 422"
}
```
```
method: DELETE,
url: {base_url}/likes/:zpid,
'headers': {
'Authorization': …
```

Likes backend api for mock data + Middleware auth 

---

client/src/components/Header/Menu.js
client/src/components/SearchOption/SearchButtons/BedSelect.js
client/src/components/SearchOption/SearchButtons/HomeType.js
client/src/components/SearchOption/SearchButtons/HomeTypeMenuItem.js
client/src/components/SearchOption/SearchButtons/PriceRange.js
client/src/components/SearchOption/SearchComponent.js
client/src/components/SearchOption/SearchOptions.js

<br />
add bell icon + delete href on Vancity ( look into focus box on on menu later?)
- Material ui has its own default style, you can't override it with styled component (unless use !important)
, so I used muiStyled instead
<br />

ISSUE 44 (continue) - Search Options Button

---

client/src/components/Header/Header.js

fix: Bug- components are rendered over nav bar

---

client/src/redux/users/service.js

<br />
send email in header as a token for auth to backend
<br />

My page: send email in header as a token for auth to backend

---

client/src/pages/MyPage/MyPage.js
client/src/styles/theme.js

<br />
Put 3 boxes on the right side of the User Profile page.
<br />

Issue 30: Put 3 Boxes in User Profile Page

---

client/src/components/Header/Header.js
client/src/components/Header/Menu.js

<br />
Also, i Changed bell to heart icon on the nav bar
<br />

ISSUE- 56 fix: Bug- components are rendered over nav bar

---

client/src/components/Property/DetailedInfo.js
client/src/components/Property/PropertyCard.js
client/src/pages/Likes/Likes.js
client/src/pages/PropertyDetail/PropertyDetail.js
client/src/redux/likes/actionTypes.js
client/src/redux/likes/reducer.js
client/src/redux/likes/service.js
client/src/redux/likes/thunks.js
server/src/controller/likes.js
server/src/models/mockLikes.js
server/src/routes/likes.js
server/src/services/likes.js

<br />
Clear All button will clear all properties from Like Page
<br />

Add Clear All button

---

client/src/components/Property/DetailedInfo.js

<br />
Increased the space between lines in the paragraph.
<br />

style: increase the space between description lines

---

client/src/pages/Likes/Likes.js

<br />
likes page footer position at the bottom of the window
<br />

fix: likes page footer position

---

client/src/components/Footer/Footer.js

<br />
open linked website in new tab
<br />

feat: open linked page in new tab

---

client/src/components/Header/Menu.js
client/src/components/User/UserCard.js
client/src/components/User/UserInfo.js
client/src/components/User/UserProfileEdit.js
client/src/pages/MyPage/MyPage.js
client/src/pages/PropertyDetail/PropertyDetail.js
client/src/redux/property/reducer.js
client/src/redux/users/reducer.js

<br />
refactor: redux init state mapped to its property
<br />

refactor: redux init state mapped to its property

---

client/src/components/User/MoreOptions.js
client/src/components/User/UserInfo.js

<br />
Adjusted height by 1vh
<br />

style: Adjust height

---

client/src/components/User/UserProfileEdit.js
package-lock.json

<br />
Changes to the buttons in the user edit form
<br />

Issue 57: Buttons in the User Edit Form

---

client/src/pages/MyPage/MyPage.js

<br />
Apologies for making changes off of a project branch. Didn't want to create a new branch for such a minor change & wanted to minimize any conflicts when merging.
<br />

Changed the width of the Box component in MyPage to 100%

---

client/src/pages/MyPage/MyPage.js

<br />
The title says it all.
<br />

style: Changed the width of the Box component in MyPage to 100%

---

client/src/components/Property/AdditonalInfo.js
client/src/components/Property/DetailedInfo.js
client/src/components/Property/MenuItems.js

<br />
Remove Sold History component, Home Value component, and Map button on the detailed page.
<br />

ISSUE-91 style: remove unnecessary components and button

---

client/src/components/Property/DetailedInfo.js

<br />
Adjusted the min-width to 100%, added a scroll bar to the description part, and commented out a button that is not useful for now. 
<br />

style: adjust min-width and add scroll bar for description

---

client/src/components/Property/MenuItems.js
client/src/pages/PropertyDetail/PropertyDetail.js

<br />
1) bug fix: having property on dependency causing infinite loop (PropertyDetailed)
2) add save button on detailed page
<br />

ISSUE 94 and 109 

---

client/src/components/SearchOption/SearchButtons/BedSelect.js
client/src/components/SearchOption/SearchButtons/HomeType.js
client/src/components/SearchOption/SearchButtons/PriceRange.js
client/src/components/SearchOption/SearchInput.js
client/src/pages/Home/Home.js
client/src/redux/home/service.js
client/src/redux/home/thunks.js
client/src/redux/search/reducer.js
client/src/redux/store.js

ISSUE-107 Redux actions - add actions/reducers for searching options

---

client/src/components/Header/Menu.js
client/src/components/Property/PropertyCard.css
client/src/components/Property/PropertyCard.js
client/src/components/Property/PropertyGrid.js
client/src/pages/Home/Home.js
client/src/pages/Likes/Likes.js

ISSUE-95,  feat add Compare btn and nvigate to compare page

---

client/src/components/Property/PropertyCard.js
client/src/components/Property/PropertyGrid.js

ISSUE-128 fix: like List (Cover String -> Integer)

---

client/src/components/Property/PropertyGrid.js
client/src/components/User/MoreOptions.js
client/src/components/User/UserCard.js
client/src/components/User/UserInfo.js
client/src/components/User/UserPageLeft.js

style: height adjustment

---

server/src/models/home.js
server/src/services/home.js

<br />
search by location title + beds
<br />

Home API: search by location title + beds

---

client/src/components/Property/PropertyCard.js

ISSUE-145 fix: like int -> string

---

client/src/components/User/UserProfileEdit.js
client/src/redux/users/service.js
server/src/controller/user.js
server/src/models/user.js
server/src/schemas/users.js
server/src/services/user.js

<br />
- Editing user profile is now saved to the DB.
- The updated info gets automatically fetched + rendered.
<br />

feat: Persistent user profile update (fetching + saving)

---

client/src/components/Property/MenuItems.js

fix : bug Save btn on detailed page

---

server/src/controller/compare.js
server/src/controller/index.js
server/src/models/compare.js
server/src/models/index.js
server/src/routes/compare.js
server/src/routes/index.js
server/src/services/compare.js
server/src/services/index.js

<br />
- add compare API
`/compare?item=zpid&item=zpid ` 
OR
`/compare?item=zpid,zpid`
<br />

feat: Compare API

---

client/src/pages/Likes/Likes.js

<br />
Simple fix for unwanted text-centering
<br />

ISSUE-180: Fix text-centering

---

client/src/redux/likes/reducer.js
client/src/redux/likes/thunks.js

ISSUE-150 fix : heart flickering bug (update redux seperately)

---

client/src/components/Property/PropertyCard.js
client/src/components/Property/PropertyImage.js
client/src/pages/Home/Home.js

fix: Property img (merge resolved)

---

client/src/pages/PropertyDetail/PropertyDetail.js

<br />
- render Nearbyhomes only if nearbyHomes list is not empty
<br />

ISSUE-192: handle nearbyhome empty state

---

client/src/components/Property/PropertyTitle.js
client/src/pages/Likes/Likes.js

<br />
A button placed to go back to prev page
<br />

feat: place a button to navigate to prev page

---

client/src/components/SearchOption/SearchButtons/BedSelect.js
client/src/components/SearchOption/SearchButtons/HomeType.js
client/src/components/SearchOption/SearchButtons/PriceRange.js
client/src/pages/Home/Home.js
client/src/redux/search/reducer.js

<br />
1. Add Reset btn to initialize all search options.
2.  Only dispatch(getListAsync(searchParams, isLogin)); when URL modified or 'Search Button is clicked"
3.  Add Search Btn
4. Search Options reflects url params 
5. 
<br />

Issue 191 1) Add Reset BTN (change backend call logic) 2) URL modification 

---

client/src/components/Footer/Footer.js

<br />
Indentation fixed (Prettier), so errors won't be thrown.
<br />

fix: indentation fixed (ISSUE-161)

---

client/src/components/Footer/Footer.js

fix: import order fixed

---

client/src/components/SearchOption/SearchButtons/PriceRange.js

<br />
fix: change the min/max logic so that can delete when num < 10
<br />

ISSUE- 201 fix: change the min/max logic so that can delete when num < 10

---

client/src/components/Property/MenuItems.js
client/src/components/Property/ShareMenu.js
client/src/pages/PropertyDetail/PropertyDetail.js

<br />
SNS share feature, currently using test url  const testUrl = 'https://www.adidas.ca/en'; until the deployment
env has updated
- Could use react-helmet to manipulate metadata for the URL? (extra feature) - might be hard to do with React though
<br />

Issue 203 SNS share

---

.github/workflow/test.yml
server/package-lock.json
server/package.json
server/src/schemas/index.js
server/src/schemas/index.test.js

feat: jest test

---

client/src/components/Property/PropertyCard.js

<br />
- resolve merge conflict
<br />

resolve merge conflict

---

server/package-lock.json
server/package.json
server/src/server.js

feat: add app.use(limiter)

---

client/src/redux/property/service.js

property api: fetch -> axios

---

server/src/server.js

<br />
- hide whitelist to .env
- .env on [notion](https://www.notion.so/thekimsplustwo/SERVER-145375431d6c4439869bc7e3aeb9c6d5?pvs=4#544cd07b9c294c32a4a55e880d96d20b)
<br />

ISSUE-238: hide whitelist to .env

---

client/src/pages/Compare/Compare.js
client/src/redux/property/actionTypes.js
client/src/redux/property/reducer.js
client/src/redux/property/service.js
client/src/redux/property/thunks.js

<br />
- add compare redux
- use of compare redux in line27-37 in client/src/pages/Compare/Compare.js
<br />
@chris718 you can use this as the base to fix the bug #215

ISSUE-215: compare redux

---

client/package.json

<br />
- disable creating source map during build client
<br />

ISSUE-250 add GENERATE_SOURCEMAP=false option on client build script

---

server/src/controller/auth.js
server/src/middleware/auth.js
server/src/middleware/googleStrategy.js

refactor: remove SERVER_URL env

---

client/src/components/Compare/CompareDeleteButton.js

<br />
- DELETE button now aligned with the other components on the Compare page
<br />

ISSUE-242: align the "delete" button with the other components

---

client/src/components/Footer/Footer.js
client/src/components/Footer/FooterSocial.js
client/src/components/Header/Menu.js
client/src/components/SearchOption/SearchInput.js
client/src/pages/Home/Home.js

<br />
Social icon does not show up when less than 700px width
<br />

ISSUE- 254 fix: minor improvement

---

client/src/components/SearchOption/SearchButtons/BedSelect.js
client/src/components/SearchOption/SearchButtons/HomeType.js
client/src/components/SearchOption/SearchButtons/PriceRange.js
client/src/components/SearchOption/SearchInput.js
client/src/components/SearchOption/SearchOptions.js
client/src/pages/Home/Home.js

ISSUE-265- Hompage feat: Homepage Mobile friendly

---

client/src/pages/Likes/Likes.js

ISSUE-265-Like page feat: Like page Mobile friendly

---

client/src/components/User/MoreOptions.js
client/src/components/User/UserProfileEdit.js
client/src/pages/MyPage/MyPage.js

ISSUE-265 Mypage feat: MyPage Mobile friendly

---

client/src/components/Property/AdditonalInfo.js
client/src/components/Property/DetailedInfo.js
client/src/components/Property/Image.js
client/src/components/Property/ImageCarousel.js
client/src/components/Property/MapBox.js
client/src/components/Property/NearByHomes.js
client/src/components/Property/PropertyCard.js
client/src/components/Property/PropertyTitle.js
client/src/components/Property/WalkScore.js
client/src/pages/PropertyDetail/PropertyDetail.js

ISSUE-265-Detail feat: Detail Page (Mobile)

---

client/src/components/Property/AdditonalInfo.js
client/src/components/Property/FeaturesSection.js
client/src/components/Property/SchoolCard.js
client/src/components/Property/TransitScore.js
client/src/components/Property/WalkScore.js
client/src/pages/PropertyDetail/PropertyDetail.js

ISSUE276 , feat: Neighbourhood details

---

client/src/components/Property/DetailedInfo.js

<br />
Refactor detailed information page
<br />

ISSUE-209: refactor: refactored DetailedInfo

---

client/src/components/Property/DetailedInfo.js

<br />
React built failure, due to format issue.
<br />

Refactor: resolve merge conflict

---

client/src/components/User/UserCard.js
client/src/components/User/UserProfileEdit.js

<br />
- Remove 'Age' from the Edit Profile window
- Refresh the page after user saves changes (so the changes are reflected instantly)
- Default profile pic
- Drop-down menu for 'Region'
<br />

ISSUE-260: Edit User Profile (front-end)

---

client/.eslintrc
client/src/components/Property/NearByHomes.js
client/src/components/Property/NearbyProperties.js
client/src/components/User/NearbyMe.js
client/src/pages/MyPage/MyPage.js

<br />
- 'Nearby Me' (properties in user's region) in user page
<br />

ISSUE-261: 'Nearby Me' in MyPage

---

client/package-lock.json
client/package.json
client/src/components/Property/AdditonalInfo.js
client/src/components/Property/PriceComparisonBar.js

Detail feat: 1) install x-chart  2) price ComparisonBar

---

client/src/pages/Compare/Compare.js
client/src/pages/Compare/Modal.js
client/src/pages/Likes/Likes.js

ISSUE 264 / feat: 1) like/compare fix height 2) compare Mobile friendly

---

client/src/components/Property/MapBox.js

<br />
https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/104462860/0b92a905-329e-4b3b-afd6-4c4dca1efbe8
<br />

ISSUE-266 fix: mapbox not update fix

---

client/src/components/Property/AdditonalInfo.js
client/src/components/Property/PriceComparisonBar.js

ISSUE-296 feat: 1) median 2) more feature

---

client/src/components/SearchOption/SearchButtons/PriceRange.js

ISSUE-286: Fix the size of min/max input boxes

---

client/src/components/User/NearbyMe.js
client/src/pages/PropertyDetail/PropertyDetail.js

<br />
- For `NearByHomes` and `NearbyMe`, only list properties whose listingStatus is "FOR_SALE"
<br />

ISSUE-294: Only list properties whose listingStatus is "FOR_SALE"

---

.github/workflows/test.yml
client/src/pages/MyPage/MyPage.js

ISSUE-298: Removed the gap in MyPage

---

client/src/components/Compare/CompareDeleteButton.js
client/src/components/Property/MenuItems.js
client/src/components/Property/PropertyCard.js
client/src/pages/Compare/Modal.js
client/src/redux/likes/reducer.js
client/src/redux/likes/thunks.js
client/src/styles/theme.js
server/src/models/compare.js
server/src/schemas/likes.js

<br />
- fix likes schema => zpid constraint
- likes rendering
<br />

ISSUE-302: likes schema & likes button rendering

---

client/src/components/Property/MenuItems.js

<br />
- onClick target: icon to the button box
<br />

ISSUE-307: likes button onclick target

---

client/src/components/Property/PriceComparisonBar.js

<br />
removed average from Additional information price detail
<br />

feat: remove average

---

client/src/components/SearchOption/neighborhoods.js

ISSUE-314 feat: remove useless locations

---

client/src/components/Property/AdditonalInfo.js
client/src/components/Property/NearByHomes.js
client/src/components/Property/NearbyProperties.js
client/src/components/User/NearbyMe.js
client/src/pages/PropertyDetail/PropertyDetail.js
client/src/redux/home/reducer.js

<br />
- base branch: ISSUE-312
- fix #312 
- fix #300 
- fix #317 
<br />
@pukkuKim 
base brach: #313 
I made updates on your pr. please add/fix if you see any updates needed

ISSUE-300, ISSUE-312, ISSUE-317 fix: neabyme, nearbyhome related issues

---

client/src/components/Property/PropertyGrid.js
client/src/components/Property/PropertyNotFound.js
server/src/services/home.js

ISSUE-270: return [] if currentpage > totalpage

---

client/package-lock.json
client/src/components/Property/PropertyGrid.js

<br />
-fix: likes page rendering issue 
<br />

ISSUE-321: likes page rendering issue

---

client/src/components/Property/PropertyGrid.js

<br />
- ISSUE-321: disable pagination button unless it's /home
<br />

ISSUE-321: disable pagination button unless it's /home

---

client/src/pages/MyPage/MyPage.js

ISSUE-325 fix: when no region data footer comes up

---

client/src/components/Property/DetailedInfo.js
client/src/pages/PropertyDetail/PropertyDetail.js

Issue 337: fix the alignment on detailed page

---

client/src/pages/Compare/Modal.js

ISSUE-334: null check to prevent errors on Compare page

---

client/src/components/Footer/Footer.js

ISSUE-336: chatbot opens in the current window

---

client/src/components/Property/PropertyGrid.js
client/src/pages/Compare/Modal.js
client/src/pages/Home/Home.js

ISSUE-330: Pagination only shows in '/home'

---

client/src/components/Footer/Footer.js

feat: chatbot opens in a new window

---

.gitignore
client/src/components/Property/DetailedInfo.js
client/src/pages/Compare/Modal.js
server/src/controller/home.js
server/src/controller/property.js
server/src/data/data.js
server/src/middleware/auth.js
server/src/schemas/index.test.js
server/src/schemas/resetDatabase.js

refactor: server - remove comment

---

client/src/components/Property/MenuItems.js

feat: housing null prevention

---

README.md

Final project
